### ISSUE TITLE
Error : No such file or directory: irtrans/models/eh_vec.npy

### ISSUE THREAD

**Issue by kindleton** [irshadbhat/python-irtrans#1]
```raveesh@ravessh-Dell-XPS:hin]$ irtrans < /tmp/hi --s eng --t hin
Traceback (most recent call last):
  File "/usr/local/bin/irtrans", line 9, in <module>
    load_entry_point('irtrans==0.1', 'console_scripts', 'irtrans')()
  File "/usr/local/lib/python2.7/dist-packages/irtrans-0.1-py2.7-linux-x86_64.egg/irtrans/**init**.py", line 53, in main
    trn = transliterator(args.format_, args.source, args.target, args.ssf_type, args.nested)
  File "/usr/local/lib/python2.7/dist-packages/irtrans-0.1-py2.7-linux-x86_64.egg/irtrans/transliterator.py", line 26, in **init**
    rit = RI_Transliterator(target)
  File "/usr/local/lib/python2.7/dist-packages/irtrans-0.1-py2.7-linux-x86_64.egg/irtrans/rom2ind.py", line 37, in **init**
    self.vec = np.load('%s/models/e%s_vec.npy' %(path, lang))[0]
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 329, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/irtrans-0.1-py2.7-linux-x86_64.egg/irtrans/models/eh_vec.npy'

```
```

**Comment by irshadbhat** [comment]
was there any error or warning during setup?

Temporary sol:  
1.   After downloading the package, go to python-irtrans/irtrans/models
2.   Unzip all files.
3.   Run setup.

See if it works.

**Comment by kindleton** [comment]
Tempororay Solution Works :D
